// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBxKQzP-qjwkWa1esFWtWzhCVGARnFTVEI',
    appId: '1:861410196177:web:4e9d5e498e30b25e2ea3f0',
    messagingSenderId: '861410196177',
    projectId: 'fir-flutter-codelab-c7501',
    authDomain: 'fir-flutter-codelab-c7501.firebaseapp.com',
    storageBucket: 'fir-flutter-codelab-c7501.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBzGZny3K8QBEFS7w3ae97CNYrKSUUFwj4',
    appId: '1:861410196177:android:e8e9f53690de1dfb2ea3f0',
    messagingSenderId: '861410196177',
    projectId: 'fir-flutter-codelab-c7501',
    storageBucket: 'fir-flutter-codelab-c7501.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCThceEm6zFnXamWDkpFJQP7w6jAd0kNn8',
    appId: '1:861410196177:ios:6489387e4c4791092ea3f0',
    messagingSenderId: '861410196177',
    projectId: 'fir-flutter-codelab-c7501',
    storageBucket: 'fir-flutter-codelab-c7501.appspot.com',
    iosBundleId: 'com.example.gtkFlutter',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCThceEm6zFnXamWDkpFJQP7w6jAd0kNn8',
    appId: '1:861410196177:ios:6489387e4c4791092ea3f0',
    messagingSenderId: '861410196177',
    projectId: 'fir-flutter-codelab-c7501',
    storageBucket: 'fir-flutter-codelab-c7501.appspot.com',
    iosBundleId: 'com.example.gtkFlutter',
  );
}
